import type { Metadata } from "next";
import { Scale } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "FOURI.IN Terms of Service — rules and guidelines for using our AI-powered mock test platform.",
};

const sections = [
  {
    title: "Acceptance of Terms",
    content: "By accessing or using FOURI.IN, you agree to be bound by these Terms of Service. If you do not agree, please do not use the platform. We reserve the right to update these terms at any time; continued use constitutes acceptance of changes.",
  },
  {
    title: "Account Registration",
    content: "You must register for an account to use our services. You agree to provide accurate, current, and complete information. You are responsible for maintaining the confidentiality of your login credentials and for all activities under your account. Notify us immediately at office@fouri.in of any unauthorised use.",
  },
  {
    title: "Use of Service",
    content: "FOURI.IN provides AI-powered mock test generation from uploaded question papers. You agree to use the platform for lawful purposes only. You may not upload content that infringes on third-party rights, contains malware, or violates any applicable laws. We reserve the right to suspend accounts that violate these terms.",
  },
  {
    title: "User Content",
    content: "You retain ownership of the question papers and content you upload. By uploading, you grant us a limited license to process, store, and analyse the content solely for providing our services. We do not claim ownership of your uploaded materials.",
  },
  {
    title: "AI-Generated Content",
    content: "Mock tests generated by our AI are for educational purposes only. While we strive for accuracy, AI-generated content may contain errors. We recommend verifying critical information independently. FOURI.IN is not responsible for exam outcomes based on AI-generated test content.",
  },
  {
    title: "Intellectual Property",
    content: "The FOURI.IN platform, including its design, code, branding, and proprietary algorithms, is owned by FOURI.IN and protected by intellectual property laws. You may not copy, modify, distribute, or reverse-engineer any part of the platform without explicit written permission.",
  },
  {
    title: "Limitation of Liability",
    content: "FOURI.IN is provided 'as is' without warranties of any kind. We are not liable for any damages arising from the use or inability to use the platform, including but not limited to loss of data, exam results, or academic performance.",
  },
  {
    title: "Termination",
    content: "We may suspend or terminate your account at any time for violation of these terms. Upon termination, your access to the platform will cease. We will delete your data in accordance with our Privacy Policy.",
  },
  {
    title: "Contact",
    content: "For questions about these terms, contact us at office@fouri.in.",
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#08080f]">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="flex items-center gap-3 mb-2">
          <Scale className="w-6 h-6 text-blue-400" />
          <h1 className="text-3xl sm:text-4xl font-bold font-heading text-[#f5f5f7]">
            Terms of Service
          </h1>
        </div>
        <p className="text-sm text-[#888899] mb-10">Last updated: May 2026</p>

        <div className="space-y-8">
          {sections.map((s) => (
            <div key={s.title}>
              <h2 className="text-lg font-semibold text-[#f5f5f7] mb-2">{s.title}</h2>
              <p className="text-sm text-[#c0c0cc] leading-relaxed">{s.content}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
