import { notFound } from "next/navigation";
import Link from "next/link";
import { examPages, generateCourseJsonLd, generateWebsiteJsonLd } from "@/lib/seo";
import { JsonLd } from "@/components/JsonLd";
import type { Metadata } from "next";

interface Props {
  params: Promise<{ examSlug: string }>;
}

export async function generateStaticParams() {
  return examPages.map((page) => ({ examSlug: page.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { examSlug } = await params;
  const page = examPages.find((p) => p.slug === examSlug);
  if (!page) return {};

  return {
    title: page.title,
    description: page.description,
    openGraph: {
      title: page.title,
      description: page.description,
      type: "website",
      locale: "en_IN",
      siteName: "FOURI.IN",
    },
    twitter: {
      card: "summary_large_image",
      title: page.title,
      description: page.description,
    },
    alternates: { canonical: `https://fouri.in/${examSlug}` },
  };
}

export default async function ExamPage({ params }: Props) {
  const { examSlug } = await params;
  const page = examPages.find((p) => p.slug === examSlug);
  if (!page) notFound();

  return (
    <>
      <JsonLd data={generateWebsiteJsonLd()} />
      <JsonLd
        data={generateCourseJsonLd(page.title, page.description, page.examFullName)}
      />

      <div className="min-h-screen flex flex-col">
        <header className="border-b border-zinc-200">
          <div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between">
            <Link href="/" className="text-xl font-bold tracking-tight">
              FOURI.IN
            </Link>
            <nav className="flex items-center gap-4">
              <Link
                href="/login"
                className="text-sm font-medium text-zinc-600 hover:text-zinc-900"
              >
                Login
              </Link>
              <Link
                href="/register"
                className="text-sm font-medium bg-zinc-900 text-white px-4 py-2 rounded-lg hover:bg-zinc-800"
              >
                Sign Up
              </Link>
            </nav>
          </div>
        </header>

        <main className="flex-1">
          <section className="max-w-6xl mx-auto px-4 py-24 text-center">
            <h1 className="text-4xl font-bold tracking-tight text-zinc-900 sm:text-5xl">
              {page.title}
            </h1>
            <p className="mt-4 text-lg text-zinc-600 max-w-2xl mx-auto">
              {page.description}
            </p>
            <div className="mt-8 flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/register"
                className="inline-flex items-center justify-center h-12 px-8 rounded-xl bg-zinc-900 text-white font-medium hover:bg-zinc-800"
              >
                Start Free Practice
              </Link>
              <Link
                href="/discover"
                className="inline-flex items-center justify-center h-12 px-8 rounded-xl border border-zinc-300 text-zinc-900 font-medium hover:bg-zinc-50"
              >
                Browse Tests
              </Link>
            </div>
          </section>

          <section className="max-w-6xl mx-auto px-4 py-20">
            <div className="grid sm:grid-cols-3 gap-8">
              <div className="p-6 rounded-2xl border border-zinc-200">
                <h3 className="font-semibold text-lg text-zinc-900">
                  Upload Past Papers
                </h3>
                <p className="mt-2 text-sm text-zinc-600">
                  Upload your {page.examFullName} question papers (PDF, JPG, PNG).
                  Our AI extracts questions instantly.
                </p>
              </div>
              <div className="p-6 rounded-2xl border border-zinc-200">
                <h3 className="font-semibold text-lg text-zinc-900">
                  AI Generates Mock Tests
                </h3>
                <p className="mt-2 text-sm text-zinc-600">
                  Get a timed mock test with randomized questions, MCQ options, and
                  answer explanations generated by AI.
                </p>
              </div>
              <div className="p-6 rounded-2xl border border-zinc-200">
                <h3 className="font-semibold text-lg text-zinc-900">
                  Practice & Track Progress
                </h3>
                <p className="mt-2 text-sm text-zinc-600">
                  Attempt tests with a live timer, review your answers, and track
                  your performance over time.
                </p>
              </div>
            </div>
          </section>

          <section className="bg-zinc-50 py-20">
            <div className="max-w-6xl mx-auto px-4 text-center">
              <h2 className="text-2xl font-bold text-zinc-900">
                Why Choose FOURI.IN?
              </h2>
              <div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-4 gap-6 text-left">
                {[
                  { title: "100% Free", desc: "No hidden charges. All features are completely free." },
                  { title: "AI-Powered", desc: "Advanced AI analyzes your papers and generates accurate tests." },
                  { title: "Instant Results", desc: "Get scores, accuracy, and detailed explanations immediately." },
                  { title: "Any Device", desc: "Mobile-first design works perfectly on phones, tablets, and desktops." },
                ].map((feat) => (
                  <div key={feat.title} className="p-4">
                    <h3 className="font-semibold text-zinc-900">{feat.title}</h3>
                    <p className="mt-1 text-sm text-zinc-600">{feat.desc}</p>
                  </div>
                ))}
              </div>
            </div>
          </section>
        </main>

        <footer className="border-t border-zinc-200 py-8">
          <div className="max-w-6xl mx-auto px-4 text-center text-sm text-zinc-500">
            &copy; {new Date().getFullYear()} FOURI.IN. All rights reserved.
          </div>
        </footer>
      </div>
    </>
  );
}
